"""empty message

Revision ID: 1ddc219dc207
Revises: 3c9f7e3122be
Create Date: 2021-11-21 21:01:12.453893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ddc219dc207'
down_revision = '3c9f7e3122be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_rating_uc', table_name='rating')
    op.drop_column('rating', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('user_rating_uc', 'rating', ['user_id', 'book_id'], unique=False)
    # ### end Alembic commands ###
