"""empty message

Revision ID: d16481a34eaa
Revises: 354347cc02d4
Create Date: 2021-11-21 19:33:57.698100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16481a34eaa'
down_revision = '354347cc02d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('rating', sa.Column('description', sa.String(length=9), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'description')
    op.drop_column('rating', 'created_date')
    # ### end Alembic commands ###
